export function renderGitHookScript(hook: "pre-commit" | "pre-push", cliCommand: string): string {
  const quotedCli = shellQuote(cliCommand);

  if (hook === "pre-commit") {
    return [
      "#!/bin/sh",
      "# Critical Gate pre-commit hook.",
      "# Generated by `critical-gate install-hooks`; review before trusting.",
      "set -eu",
      'TASK="${CRITICAL_GATE_TASK:-Pre-commit staged change}"',
      `${quotedCli} check --staged --task "$TASK" --format repair --fail-on blocker`,
      ""
    ].join("\n");
  }

  return [
    "#!/bin/sh",
    "# Critical Gate pre-push hook.",
    "# Generated by `critical-gate install-hooks`; review before trusting.",
    "set -eu",
    'TASK="${CRITICAL_GATE_TASK:-Pre-push branch change}"',
    'BASE="${CRITICAL_GATE_BASE:-origin/main}"',
    `${quotedCli} check --base "$BASE" --task "$TASK" --format repair --fail-on high`,
    ""
  ].join("\n");
}

function shellQuote(value: string): string {
  if (/^[A-Za-z0-9_./:-]+$/.test(value)) {
    return value;
  }

  return `'${value.replaceAll("'", "'\\''")}'`;
}
